---
- name: Restore backuped database
  community.postgresql.postgresql_db:
    login_host: "{{ odoo_config_db_host }}"
    port: "{{ odoo_config_db_port | int }}"
    ssl_mode: "{{ odoo_config_db_sslmode }}"
    login_user: "{{ odoo_postgresql_login_user }}"
    login_password: "{{ odoo_postgresql_login_password }}"
    owner: "{{ odoo_config_db_user }}"
    name: "{{ odoo_config_db_name }}"
    state: restore
    target: "{{ odoo_update_database_backup }}"
    target_opts: "--clean --create"

- name: Restore backuped filestore
  when: odoo_backup_filestore
  delegate_to: "{{ inventory_hostname }}"
  ansible.posix.synchronize:
    archive: true
    compress: false
    delete: true
    recursive: true
    links: true
    group: true
    owner: true
    src: "{{ odoo_update_datadir_backup }}/{{ item }}/"
    dest: "{{ odoo_config_data_dir }}/{{ item }}/"
  loop:
    - addons
    - filestore
