---
- name: Delete database backup file
  when: odoo_delete_database_backup
  ansible.builtin.file:
    path: "{{ odoo_update_database_backup }}"
    state: absent
  ignore_errors: true
  register: ignore_errors_odoo_delete_database_backup

- name: Delete filestore copy
  when: odoo_delete_datadir_backup
  ansible.builtin.file:
    path: "{{ odoo_update_datadir_backup }}"
    state: absent
  ignore_errors: true
  register: ignore_errors_odoo_delete_datadir_backup
