---

- name: Install nginx (Debian)
  apt:
    name: nginx
    state: latest
    install_recommends: no
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install nginx (RedHat)
  yum:
    name: nginx
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Create Nginx cache directory
  file:
    path: "{{ odoo_nginx_cache_folder | dirname }}"
    state: directory
    mode: 0775
    owner: "www-data"
    group: "www-data"

- name: Setup maintenance page
  template:
    src: "{{ item }}"
    dest: "{{ odoo_nginx_document_root }}"
  loop:
    - maintenance.html
    - maintenance.json

- name: Setup site configuration file
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Enable new site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx
