---

- name: Add Odoo system user
  user:
    name: "{{ odoo_user }}"
    shell: /bin/bash
    password: "{{ odoo_user_passwd }}"
    update_password: on_create
    system: "{{ odoo_user_system }}"
  when: odoo_set_user

- name: Configure PostgreSQL
  include_tasks:
    file: configure_postgresql.yml
    apply:
      tags: configuration
  when: odoo_set_postgresql

- name: Configure Logrotate
  include_tasks:
    file: configure_logrotate.yml
    apply:
      tags: configuration
  when: odoo_set_logrotate

- name: Configure Odoo
  include_tasks:
    file: configure_odoo.yml
    apply:
      tags: configuration
  when: odoo_set_configuration

- name: Configure Nginx
  include_tasks:
    file: configure_nginx.yml
    apply:
      tags: configuration
  when: odoo_set_nginx

- name: Configure service
  include_tasks:
    file: configure_service.yml
    apply:
      tags: configuration
  when: odoo_set_service
