---
- name: Add the PostgreSQL signing key (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add the PostgreSQL repository into sources list (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Add the PostgreSQL repository into sources list (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum_repository:
    name: "pgdg{{ odoo_postgresql_version or '' }}"
    baseurl: >
      "https://download.postgresql.org/pub/repos/yum/reporpms/"
      "EL-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"
      "/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: Update APT cache (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Install PostgreSQL client (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "postgresql-client{{ odoo_postgresql_version and '-%s' % odoo_postgresql_version or '' }}"
    state: present

- name: Install PostgreSQL client (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: "postgresql{{ odoo_postgresql_version or '' }}"
    state: present

- name: Install Ansible PostgreSQL dependencies (Debian)
  when:
    - ansible_os_family == 'Debian'
    - odoo_postgresql_set_user or odoo_postgresql_active_unaccent
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Install Ansible PostgreSQL dependencies (RedHat)
  when:
    - ansible_os_family == 'RedHat'
    - odoo_postgresql_set_user or odoo_postgresql_active_unaccent
  ansible.builtin.yum:
    name: python3-psycopg2
    state: present

- name: PostgreSQL - Add or update the database user without password
  when:
    - odoo_postgresql_set_user
    - not odoo_config_db_password
  community.postgresql.postgresql_user:
    name: "{{ odoo_config_db_user }}"
    role_attr_flags: "{{ odoo_postgresql_user_role_attr }}"
    login_host: "{{ odoo_config_db_host }}"
    port: "{{ odoo_config_db_port | int }}"
    ssl_mode: "{{ odoo_config_db_sslmode }}"
    login_user: "{{ odoo_postgresql_login_user }}"
    login_password: "{{ odoo_postgresql_login_password }}"
  ignore_errors: true
  register: ignore_errors_odoo_postgresql_user

- name: PostgreSQL - Add or update the database user with password
  when:
    - odoo_postgresql_set_user
    - odoo_config_db_password
  community.postgresql.postgresql_user:
    name: "{{ odoo_config_db_user }}"
    role_attr_flags: "{{ odoo_postgresql_user_role_attr }}"
    password: "{{ odoo_config_db_password }}"
    login_host: "{{ odoo_config_db_host }}"
    port: "{{ odoo_config_db_port | int }}"
    ssl_mode: "{{ odoo_config_db_sslmode }}"
    login_user: "{{ odoo_postgresql_login_user }}"
    login_password: "{{ odoo_postgresql_login_password }}"
  ignore_errors: true
  register: ignore_errors_odoo_postgresql_user

- name: PostgreSQL - Grant privileges
  when: odoo_postgresql_set_user
  community.postgresql.postgresql_membership:
    login_host: "{{ odoo_config_db_host }}"
    port: "{{ odoo_config_db_port | int }}"
    ssl_mode: "{{ odoo_config_db_sslmode }}"
    login_user: "{{ odoo_postgresql_login_user }}"
    login_password: "{{ odoo_postgresql_login_password }}"
    groups: "{{ odoo_config_db_user }}"
    target_roles: "{{ odoo_postgresql_login_user }}"

- name: PostgreSQL - Activate the 'unaccent' extension on databases
  when: odoo_postgresql_active_unaccent
  community.postgresql.postgresql_ext:
    name: unaccent
    db: "{{ odoo_config_db_template }}"
    login_host: "{{ odoo_config_db_host }}"
    port: "{{ odoo_config_db_port | int }}"
    ssl_mode: "{{ odoo_config_db_sslmode }}"
    login_user: "{{ odoo_postgresql_login_user }}"
    login_password: "{{ odoo_postgresql_login_password }}"
