---
- name: Generate odoo init script
  when: odoo_init
  ansible.builtin.template:
    src: odoo.init
    dest: /etc/init.d/{{ odoo_service }}
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
    force: "{{ odoo_config_force and 'yes' or 'no' }}"
    backup: true
  notify: Restart Odoo

- name: Reload systemd
  when: ansible_service_mgr == 'systemd'
  ansible.builtin.systemd:
    daemon-reload: true

- name: Enable odoo service
  when: odoo_init
  ansible.builtin.service:
    name: "{{ odoo_service }}"
    enabled: "{{ odoo_service_starts_on_boot }}"
    state: started
  become: true

- name: Disable odoo service
  when: odoo_init
  ansible.builtin.service:
    name: "{{ odoo_service }}"
    enabled: "{{ odoo_service_starts_on_boot }}"
    state: stopped
  become: true
