---
- name: Install nginx (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: nginx
    state: present
    install_recommends: false
    update_cache: true

- name: Install nginx (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: nginx
    state: present
    update_cache: true

- name: Create Nginx cache directory
  ansible.builtin.file:
    path: "{{ odoo_nginx_cache_folder | dirname }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rx"
    owner: "www-data"
    group: "www-data"

- name: Setup maintenance page
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ odoo_nginx_document_root }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - maintenance.html
    - maintenance.json

- name: Setup site configuration file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    mode: "u=rw,g=r,o=r"
  notify: Restart Nginx

- name: Enable new site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx
