---
- name: Create log directory
  ansible.builtin.file:
    path: "{{ odoo_logdir }}"
    state: directory
    owner: "{{ odoo_user }}"
    group: "{{ odoo_user }}"
    mode: "u=rwx,g=rx,o=rx"
    force: false

- name: Setup logrotate configuration file
  ansible.builtin.template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ odoo_service }}"
    mode: "u=rw,g=r,o=r"
