---
- name: Add Odoo system user
  when: odoo_set_user
  ansible.builtin.user:
    name: "{{ odoo_user }}"
    shell: /bin/bash
    password: "{{ odoo_user_passwd }}"
    update_password: on_create
    system: "{{ odoo_user_system }}"

- name: Configure PostgreSQL
  when: odoo_set_postgresql
  ansible.builtin.include_tasks:
    file: configure_postgresql.yml
    apply:
      tags: configuration

- name: Configure Logrotate
  when: odoo_set_logrotate
  ansible.builtin.include_tasks:
    file: configure_logrotate.yml
    apply:
      tags: configuration

- name: Configure Odoo
  when: odoo_set_configuration
  ansible.builtin.include_tasks:
    file: configure_odoo.yml
    apply:
      tags: configuration

- name: Configure NewRelic
  when: odoo_set_newrelic
  ansible.builtin.include_tasks:
    file: configure_newrelic.yml
    apply:
      tags: packages

- name: Configure Nginx
  when: odoo_set_nginx
  ansible.builtin.include_tasks:
    file: configure_nginx.yml
    apply:
      tags: configuration

- name: Configure fail2ban
  when: odoo_set_fail2ban
  ansible.builtin.include_tasks:
    file: configure_fail2ban.yml
    apply:
      tags: configuration

- name: Configure service
  when: odoo_set_service
  ansible.builtin.include_tasks:
    file: configure_service.yml
    apply:
      tags: configuration
