---
- name: Create Odoo configuration file directory
  ansible.builtin.file:
    path: "{{ odoo_config_file | dirname }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ odoo_sources_owner }}"
    group: "{{ odoo_user }}"

- name: Setup Odoo configuration file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ odoo_config_file }}"
    owner: "{{ odoo_sources_owner }}"
    group: "{{ odoo_user }}"
    mode: "u=rw,g=rw,o="
    force: "{{ odoo_config_force }}"
    backup: true
  with_first_found:
    - files:
        - "odoo-{{ odoo_version }}.conf"
        - "odoo.conf"
      paths: "../templates"
  notify: Restart Odoo
