---
- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
    virtualenv: "{{ odoo_virtualenv }}"
    virtualenv_site_packages: true

- name: Install Odoo dependencies (pip)
  ansible.builtin.pip:
    name: "{{ (odoo_pip_packages | default([])) + (odoo_extra_pip_packages | default([])) | flatten }}"
    virtualenv: "{{ odoo_virtualenv }}"

- name: Check if a PIP requirements file exists
  ansible.builtin.stat:
    path: "{{ odoo_extra_pip_requirements }}"
  register: pip_requirements

- name: Install Odoo dependencies (pip requirements)
  when: pip_requirements.stat.exists
  ansible.builtin.pip:
    requirements: "{{ odoo_extra_pip_requirements }}"
    virtualenv: "{{ odoo_virtualenv }}"
