---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install wkhtmltopdf dependencies (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "{{ odoo_wkhtmltox_depends }}"
    state: present

- name: Install wkhtmltopdf dependencies (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: "{{ odoo_wkhtmltox_depends }}"
    state: present

- name: Install wkhtmltopdf (Debian)
  when:
    - ansible_os_family == 'Debian'
    - "'wkhtmltopdf' not in ansible_facts.packages"
  ansible.builtin.apt:
    deb: "{{ odoo_wkhtmltox_url }}"
    state: present
    force: true

- name: Install wkhtmltopdf (RedHat)
  when:
    - ansible_os_family == 'RedHat'
    - "'wkhtmltopdf' not in ansible_facts.packages"
  ansible.builtin.yum:
    name: "{{ odoo_wkhtmltox_url }}"
    state: present
