---

- name: Check if wkhtmltopdf is already installed (Debian)
  command: dpkg -l wkhtmltopdf
  become: yes
  ignore_errors: yes
  register: wkhtmltopdf_deb_package
  when: ansible_os_family == 'Debian'

- name: Check if wkhtmltopdf is already installed (RedHat)
  command: rpm -q wkhtmltopdf
  become: yes
  ignore_errors: yes
  register: wkhtmltopdf_rpm_package
  when: ansible_os_family == 'RedHat'

- name: Download wkhtmltopdf
  get_url:
    url: "{{ odoo_wkhtmltox_url }}"
    dest: /tmp
  ignore_errors: yes
  register: wkhtmltopdf_download
  when: wkhtmltopdf_deb_package is failed or wkhtmltopdf_rpm_package is failed

- name: Install wkhtmltopdf dependencies (Debian)
  apt:
    name: "{{ odoo_wkhtmltox_depends }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install wkhtmltopdf dependencies (RedHat)
  yum:
    name: "{{ odoo_wkhtmltox_depends }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install wkhtmltopdf (Debian)
  apt:
    deb: "{{ wkhtmltopdf_download.dest }}"
    force: yes
  when:
    - wkhtmltopdf_deb_package is failed
    - ansible_os_family == 'Debian'

- name: Install wkhtmltopdf (RedHat)
  yum:
    name: "{{ wkhtmltopdf_download.dest }}"
  when:
    - wkhtmltopdf_rpm_package is failed
    - ansible_os_family == 'RedHat'
