---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Download nodejs sources
  when: "'nodejs' not in ansible_facts.packages"
  get_url:
    url: "{{ odoo_nodejs_source }}"
    dest: /tmp
    mode: u+x
  register: node_script

- name: Install nodejs sources
  when: node_script.changed
  shell: "{{ node_script.dest }}"

- name: Install nodejs (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install nodejs (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: Check that '/usr/bin/nodejs' exists
  ansible.builtin.stat:
    path: /usr/bin/nodejs
  register: nodejs_executable

- name: Check that '/usr/local/bin/node' exists
  ansible.builtin.stat:
    path: /usr/local/bin/node
  register: node_executable

- name: Add symlink '/usr/local/bin/node'
  ansible.builtin.file:
    src: /usr/bin/nodejs
    dest: /usr/local/bin/node
    state: link
  when: nodejs_executable.stat.exists and not node_executable.stat.exists

- name: Install Odoo dependencies (npm)
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop: "{{ (odoo_npm_packages | default([])) + (odoo_extra_npm_packages | default([])) | flatten }}"
