---
- name: Update APT cache (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Update all packages to their latest version (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install system packages
  ansible.builtin.include_tasks:
    file: install_system_packages.yml
    apply:
      tags: packages

- name: Install PyPI packages
  ansible.builtin.include_tasks:
    file: install_pip_packages.yml
    apply:
      tags: packages

- name: Install NodeJS packages
  ansible.builtin.include_tasks:
    file: install_npm_packages.yml
    apply:
      tags: packages

- name: Install wkhtmltopdf
  when: odoo_wkhtmltox_url is defined
  ansible.builtin.include_tasks:
    file: install_wkhtmltopdf.yml
    apply:
      tags: packages
