---
- name: Install required tools (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "{{ (odoo_required_tools | default([])) + (odoo_extra_tools | default([])) | flatten }}"
    state: present

- name: Install required tools (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: "{{ (odoo_required_tools | default([])) + (odoo_extra_tools | default([])) | flatten }}"
    state: present

- name: Install Odoo dependencies (Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "{{ (odoo_system_packages | default([])) + (odoo_extra_system_packages | default([])) | flatten }}"
    state: present

- name: Install Odoo dependencies (RedHat)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: "{{ (odoo_system_packages | default([])) + (odoo_extra_system_packages | default([])) | flatten }}"
    state: present
