---
- name: Restart Odoo
  when:
    - odoo_init
    - odoo_restart
  ansible.builtin.service:
    name: "{{ odoo_service }}"
    state: restarted
  become: true

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true
